### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by jmrichardson** [MislavSag/trademl#8]
Hi, 

I came across your repo looking for someone that had similar ideas as mine for a trading system.  I was thinking of creating one with the help of python, backtrader and mlfinlab as a base.  It looks like you have started to put together a framework with these components.  If you are interested in partnering, let me know.  

Best,
John

**Comment by MislavSag** [comment]
Hi John,

You are right, I am trying to use mlfinlab package as the core for my ml strategies. This repo are just some of my help functions and examples. I also make PRs to mlfinlab when thinking necessary. Well, I am developing my strategy alone, so help/collaboration would make my life easier. Do you work in the industry or just developing strategies for yourself? We can move the chat to some other platform (telegram/slack or similar).

**Comment by jmrichardson** [comment]
Hi, I have telegram installed but would prefer to leave my email here vs phone number, over email we can move to telegram.  My obfuscated email address is jmrichardson AT gmail.  I'm in the IT industry but enjoy developing in python, ML and just getting started in trading.
